# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_cpp <- function(data, unique = TRUE, freq = TRUE) {
    .Call('equi_count_cpp', PACKAGE = 'equi', data, unique, freq)
}

